#!/bin/bash

# Bring up wifi if we're not on the network

until $(curl --output /dev/null --silent --head --fail http://www.google.com); do

    echo "Waiting for internet connection to be set up via WiFi..."

    if [[ "$INITSYSTEM" == "on" ]]; then
        DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host_run/dbus/system_bus_socket npm start
    else
        npm start
    fi

done

# Run the gateway

/go/bin/ttgate

# Loop rather than exiting

while true
do
    echo "App exited but container is still running to allow web terminal access"
    sleep 3600
done
